In [19]:
import json
import numpy as np
import os, sys
sys.path.append('../classification')
import classify_nested
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectKBest
from importlib import reload

In [20]:
reload(classify_nested)
X = np.random.randn(10*150).reshape(10,150)
y = np.array([np.random.random_integers(2)-1 for i in range(10)])
print(X)
print(y)

print(classify_nested.customScore(X,y))
print(f_classif(X,y))

[[-0.21691158  0.90048644  0.16600168 ..., -0.19508829 -0.22549076
   2.31706733]
 [-1.8505463  -1.21364341  0.88501355 ..., -1.44516826 -0.32793582
  -1.09191327]
 [ 0.25348016 -0.70214711  0.97341693 ...,  0.02497137  1.90734062
   0.13467117]
 ..., 
 [-1.85888995  0.83504587  2.00605694 ..., -0.11576481 -0.14075465
   0.10064678]
 [ 0.29062942  0.185243    0.10799425 ..., -0.19272408 -0.65237792
  -1.65459477]
 [ 0.69825641 -0.21716935 -1.71415687 ...,  0.72428301 -1.25100438
   0.63857934]]
[0 1 0 1 1 1 1 0 1 1]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
(array([ 40.        ,  38.04917698,  36.19349672,  34.4283

/usr/lib/python3.6/site-packages/ipykernel/__main__.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 2 + 1) instead
  app.launch_new_instance()


In [11]:
selector = SelectKBest(k=2)
selector.fit(X,y)
selector.transform(X)

array([[ 0.5744472 ,  1.28897927],
       [ 0.36782748, -0.35009266],
       [-0.17340258,  0.33533762],
       [ 1.6599005 ,  2.36536355],
       [ 0.27636816,  0.62948091],
       [-0.86466352, -0.03451785],
       [-0.5960366 ,  0.32873435],
       [-0.12540493, -1.18958388],
       [-0.32582336, -0.92904409],
       [ 1.42539249,  0.72388889]])

In [15]:
selector = SelectKBest(classify_nested.customScore, k=2)
selector.fit(X,y)
selector.transform(X)


<function classify_nested.customScore>